import image1 from "@/assets/images/sliders/1.jpg";
import image2 from "@/assets/images/sliders/2.jpg"
import image3 from "@/assets/images/sliders/3.jpg";
import image4 from "@/assets/images/sliders/4.jpg"
import image5 from "@/assets/images/sliders/5.jpg";


export const carouselImages = [  image1,image2,image3,image4,image5];


export const cloneBrands = [
    "Afnan",
    "Alaia Paris",
    "Alexandria Fragrances",
    "Amouage",
    "Angela Ciampagna",
    "Argos",
    "Armaf",
    "Astrophil & Stella",
    "Atelier des Ors",
    "Attar Collection",
    "BDK",
    "BornToStandOut",
    "Burberry",
    "By Kilian",
    "Byredo",
    "Carner Barcelona",
    "Chanel",
    "Chloé",
    "City Rhythm",
    "Creed",
    "Dior",
    "Diptyque",
    "Dolce & Gabbana",
    "DS&Durga",
    "Elizabeth Arden",
    "Franck Boclet",
    "Giardini Di Toscana",
    "Giorgio Armani",
    "Gucci",
    "Imaginary Authors",
    "Initio Parfums Prives",
    "Jean Paul Gaultier",
    "Juliette Has A Gun",
    "Lalique",
    "Le Labo",
    "Les Liquides Imaginaires",
    "Les Soeurs de Noe",
    "Loewe",
    "L'Orchestre",
    "Mad et Len",
    "Maison Francis Kurkdjian",
    "Maison Martin Margiela",
    "Maison Matine",
    "Mancera",
    "Marc Jacobs",
    "Marie Jeanne",
    "Matiere Premiere",
    "Montale",
    "MontBlanc",
    "Mugler",
    "NARCISO RODRIGUEZ",
    "Nasomatto",
    "NISHANE",
    "ONCE",
    "Ormonde Jayne",
    "Orto Parisi",
    "Paco Rabanne",
    "Parfums De Marly",
    "Roja Dove",
    "Salvatore Ferragamo",
    "Tamburins",
    "The Merchant of Venice",
    "Theodoros Kalotinis",
    "Thomas Kosmala",
    "Tom Ford",
    "Valentino",
    "Van Cleef & Arpels",
    "Versace",
    "Viktor & Rolf",
    "Xerjoff",
    "Yves Saint Laurent"
]